/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

//GpioA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE+0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE+0x0c)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE+0x08)

//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE+0x04)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE+0x00)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE+0x0c)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE+0x08)

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE+0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE+0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE+0x00)




void clock_init()
{
	RCC_APB2ENR |= (1<<2);   // Enable Gpio portA clock
	RCC_APB2ENR |= (1<<3);	//Enable Gpio portB clock
	}
void Gpio_init(){
// reset registers to 0x00 value
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;
	GPIOA_ODR =0;

	//input mode reset state
	GPIOA_CRL &=~(0b11<<4);
	//CNF0 01 Floating input
	GPIOA_CRL |=(0b01<<6);

	//PB1 OUTPUT PUSH PULL mode
	//01: Output mode, max speed 10 MHz
	GPIOB_CRL |=(0b01<<4);
	//00: General purpose output push-pull
	GPIOB_CRL &=~(0b11<<6);

	//input mode reset state
	GPIOA_CRH &=~(0b11<<20);
	//CNF0 01 Floating input
	GPIOA_CRH |=(0b01<<22);

	//PB7 OUTPUT PUSH PULL mode
	//01: Output mode, max speed 10 MHz
	GPIOB_CRH |=(0b01<<20);
	//00: General purpose output push-pull
	GPIOB_CRH &=~(0b11<<22);


}

void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i =0 ; i < time; i++)
		for(j= 0 ; j < 255; j++);
}

int main(void)
{

   uint32_t pressed =0;
	clock_init();
	Gpio_init();


   while(1){
	   if((((GPIOA_IDR & (1<<1))>>1) == 0) && !pressed ){
		   GPIOB_ODR ^= (1<<1);
		   pressed = 1;
	   }
	   if((((GPIOA_IDR & (1<<1))>>1) == 1)  ){

		   pressed = 0;
	   }
	   if(((GPIOA_IDR & (1<<13))>>13) == 1){
		   GPIOB_ODR ^= (1<<13);
	   }
	   wait_ms(1);

   }
}


