/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define MCU_ACT_AS_SLAVE
//#define MCU_ACT_AS_MASTRE


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../stm32_F103C6_drivers/inc/stm32f103c6.h"
#include "../stm32_F103C6_drivers/inc/stm32_F103C6_gpio_driver.h"
#include "../HAL/inc/lcd_driver.h"
#include <keypad.h>
#include "../stm32_F103C6_drivers/inc/stm32f103c6_EXTI_driver.h"
#include "../stm32_F103C6_drivers/inc/stm32f103c6_USART_driver.h"
#include "../stm32_F103C6_drivers/inc/stm32f103c6_SPI_driver.h"


	uint16_t ch;

void clock_init(){

	//Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

}

void SPI_IRQ_CallBack(struct S_IRQ_SRC irq_src){

	if(irq_src.RXNE){
		ch = 0x0f;
		MCAL_SPI_TX_RX(SPI1, &ch, disable);
		MCAL_UART_SendData(USART1, &ch,enable);
	}


}

void UART_IRQ_CallBack(){

#ifdef MCU_ACT_AS_MASTRE
	MCAL_UART_ReceivData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);

	//Send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
    MCAL_SPI_TX_RX(SPI1, &ch, enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif

}

int main(void)
{
	clock_init();



	//==========================SPI Init===============================
	//PA4 : SPI_NSS
	//PA5 : SPI_SCK
	//PA6 : SPI_MISO
	//PA7 : SPI_MOSI
	SPI_Config spiCFG;

	//common Configuration (Master and Slave)
	spiCFG.CLKPhase = SPI_CLKPhase_secondEdge ;
	spiCFG.CLKPolarity = SPI_CLKPolarity_HIGH;
	spiCFG.Frame_Format = SPI_Frame_Format_MSBfirst;
	spiCFG.DataSize = SPI_DataSize_8BIT;
	//ASSUME by defalute pclk2 = 8MHZ
	spiCFG.BaudRate_Prescaler = SPI_BaudRate_Prescaler_8;
	spiCFG.Communication_Mode =SPI_Direction_2LINE;

#ifdef MCU_ACT_AS_MASTRE
	spiCFG.Device_Mode = SPI_Device_Mode_MASTER;
	spiCFG.IRQ_Enable = SPI_IRQ_Enable_NONE;
	spiCFG.NSS = SPI_NSS_SoftWareSlave_Set;
	spiCFG.P_IRQ_CallBack = NULL;

	//configure ss portA pin4 GPIO
		GPIO_PinConfig_t pinCFG;
		pinCFG.GPIO_PinNumber = GPIO_PIN_4;
		pinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
		pinCFG.GPIO_Output_Speed = GPIO_SPEED_10M;
		MCAL_GPIO_Init(GPIOA, &pinCFG);

		//Force the slave slect HIGH idle mode
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif

#ifdef MCU_ACT_AS_SLAVE
	spiCFG.Device_Mode = SPI_Device_Mode_SLAVE;
	spiCFG.IRQ_Enable = SPI_IRQ_Enable_RXNE;
	spiCFG.NSS = SPI_NSS_Hard_Slave;
	spiCFG.P_IRQ_CallBack = SPI_IRQ_CallBack ;
#endif

	MCAL_SPI_Init(SPI1, &spiCFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);




	//================UART Init===========================
		UART_Config uartCFG;

		uartCFG.BaudRate = UART_BaudRate_115200 ;
		uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE;
		uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
		uartCFG.P_IRQ_CallBack = UART_IRQ_CallBack;
		uartCFG.Parity = UART_Parity__NONE;
		uartCFG.Payload_Length = UART_Payload_Length_8B;
		uartCFG.StopBits = UART_StopBits__1;
		uartCFG.USART_Mode = UART_MODE_TX_RX;


		MCAL_UART_Init(USART1, &uartCFG);
		MCAL_UART_GPIO_Set_Pins(USART1);
	while(1){


	}
}
