/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define GPIO_BASE 0x40010800
#define GPIO_CRH *(volatile uint32_t *)(GPIO_BASE+0x04)
#define GPIO_ODR *(volatile uint32_t *)(GPIO_BASE+0x0c)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE+0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE+0x04)
int main(void)
{
	volatile int i;

	RCC_APB2ENR |= (1<<2);   // Enable Gpio portA clock
	RCC_CFGR |= (0b100 << 11); //APB2 2mhz divide by 4
	RCC_CFGR |= (0b101 << 8); //APB 4mhz divide by 2
	GPIO_CRH &=0xff0fffff;   // GPIO init
	GPIO_CRH |=0x00200000;
   while(1){

	   GPIO_ODR |=(1<<13);
	   for(i=0;i<5000;i++);
	   GPIO_ODR &=~(1<<13);
	   for(i=0;i<5000;i++);
   }
}
